export const ELEMENT_TEXT = Symbol.for('ELEMENT_TEXT'); // 文本元素
export const TAG_ROOT = Symbol.for('TAG_ROOT'); // 根Fiber
export const TAG_HOST = Symbol.for('TAG_HOST'); // 函数组件 类组件
export const TAG_TEXT = Symbol.for('TAG_TEXT'); // 文本节点
export const PLACEMENT = Symbol.for('PLACEMENT'); // 插入节点
export const UPDATE = Symbol.for('UPDATE'); // 更新节点
export const DELETION = Symbol.for('DELETION'); // 删除
export const TAG_CLASS = Symbol.for('TAG_CLASS'); // 类组件
export const TAG_FUNCTION = Symbol.for('TAG_FUNCTION'); //函数组件
